# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'ChuckNorrisApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya/Combine', '~> 15.0'
  # Pods for ChuckNorrisApp

  target 'ChuckNorrisAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisAppUITests' do
    # Pods for testing
  end

end
